### ISSUE TITLE
Set Up ESLint/Prettier

### ISSUE THREAD

**Issue by SureshPradhana** [SureshPradhana/art#17]
Configure ESLint and Prettier for code quality and consistent formatting.

**Comment by GamilaCoding** [comment]
Hi SureshPradhana,
 I'd like to work on this issue. Could you please assign it to me? Thanks!

**Comment by SureshPradhana** [comment]
@GamilaCoding, I've assigned it to you.

**Comment by SureshPradhana** [comment]
@GamilaCoding, thanks for the contribution
